import { SarcomShape } from '../shapes/SarcomShapeUtil'
import { SarcomShapeProps } from '../types'

/**
 * Generate a human-readable TOML scenario file from the current shapes.
 * This is a mockup design aid only — NOT the production protocol format.
 */
export function exportToml(shapes: SarcomShape[]): string {
  const now = new Date().toISOString()

  const lines: string[] = [
    '# SARCOM Mockup Scenario',
    '# Generated by sarcom-mockup-studio — NOT a production format',
    '# This file is for UX design reference only.',
    '',
    '[scenario]',
    `name        = "My SARCOM Scenario"`,
    `generated   = "${now}"`,
    `version     = "mockup-v1"`,
    `canvas_w    = 800`,
    `canvas_h    = 480`,
    '',
  ]

  const nodes = shapes.filter(s =>
    ['tag', 'relay', 'gateway'].includes(s.props.ui_kind),
  )
  const overlays = shapes.filter(s =>
    !['tag', 'relay', 'gateway'].includes(s.props.ui_kind),
  )

  for (const shape of nodes) {
    const p = shape.props as SarcomShapeProps
    lines.push('[[nodes]]')
    lines.push(`node_id        = "${p.node_id}"`)
    lines.push(`label          = "${p.label}"`)
    lines.push(`ui_kind        = "${p.ui_kind}"`)
    lines.push(`state          = "${p.state}"`)
    lines.push(`last_seen      = "${p.last_seen_text}"`)
    lines.push(`coords         = "${p.coords_text}"`)
    lines.push(`battery        = "${p.battery_text}"`)
    lines.push(`canvas_x       = ${Math.round(shape.x)}`)
    lines.push(`canvas_y       = ${Math.round(shape.y)}`)
    lines.push('')
  }

  if (overlays.length > 0) {
    lines.push('# UI overlay elements (informational)')
    for (const shape of overlays) {
      const p = shape.props as SarcomShapeProps
      lines.push('[[overlays]]')
      lines.push(`ui_kind  = "${p.ui_kind}"`)
      lines.push(`label    = "${p.label}"`)
      lines.push(`canvas_x = ${Math.round(shape.x)}`)
      lines.push(`canvas_y = ${Math.round(shape.y)}`)
      lines.push(`w        = ${Math.round(p.w)}`)
      lines.push(`h        = ${Math.round(p.h)}`)
      lines.push('')
    }
  }

  return lines.join('\n')
}
